batch_size: 1
channels: 24
check_val: 5
csv_test_img: ./test.csv
csv_train_img: ./train.csv
csv_val_img: ./validation.csv
dropout: 0.0
embed_dim: 256
inputchannels: 1
max_epochs: 100
n_embed: 1024
num_classes: 3
num_workers: 4
output_root: ./data/Prostate/outputprostatefinal
w_asd: 0.1
w_d: 0.8
w_hd: 0.1
