"""Utilities to inspect token grids generated by the PRIM tokenizer.

This script loads token tensors from disk, prints basic statistics, and saves:
1. A central slice visualization for one sample.
2. A histogram of token frequencies.

Expected input shapes:
- (N, H, W, D)
- (H, W, D)
- (H, W)
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import torch


BASE_DIR = Path("./data/Prostate/outputprostatefinal")
FILES = ("tokens_train.pt", "tokens_val.pt", "tokens_test.pt")
OUT_DIR = BASE_DIR / "tokens_plots"


def load_tokens(path: Path) -> Any:
    """Load a serialized token object from disk on CPU."""
    return torch.load(path, map_location="cpu", weights_only=False)


def extract_token_tensor(obj: Any) -> torch.Tensor | None:
    """Extract a token tensor from a loaded object.

    Supported formats:
    - A raw tensor
    - A dictionary containing a tensor under the key "tokens"
    """
    if isinstance(obj, torch.Tensor):
        return obj

    if isinstance(obj, dict):
        tokens = obj.get("tokens")
        if isinstance(tokens, torch.Tensor):
            return tokens

    return None


def summarize_tokens(name: str, tokens: torch.Tensor) -> None:
    """Print basic information about a token tensor."""
    print(f"\n=== {name} ===")
    print("type:", type(tokens))
    print("shape:", tuple(tokens.shape))
    print("dtype:", tokens.dtype)
    print("min/max:", int(tokens.min().item()), int(tokens.max().item()))
    print("#unique:", int(torch.unique(tokens).numel()))


def plot_slice(name: str, tokens: torch.Tensor, out_dir: Path) -> None:
    """Save one representative 2D visualization from a token grid.

    Accepted shapes:
    - (N, H, W, D): plots the central z-slice of the first sample
    - (H, W, D): plots the central z-slice
    - (H, W): plots the 2D grid directly
    """
    sample = tokens[0] if tokens.dim() == 4 else tokens

    if sample.dim() == 3:
        z_index = sample.shape[-1] // 2
        image = sample[:, :, z_index].detach().cpu().numpy()
        title = f"{name} | slice z={z_index}"
    elif sample.dim() == 2:
        image = sample.detach().cpu().numpy()
        title = f"{name} | 2D"
    else:
        print(f"[WARN] {name}: unsupported tensor rank for slice plot: dim={sample.dim()}")
        return

    out_path = out_dir / f"{name}_slice.png"
    plt.figure()
    plt.imshow(image, interpolation="nearest")
    plt.title(title)
    plt.axis("off")
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()
    print("Saved:", out_path)


def plot_histogram(name: str, tokens: torch.Tensor, out_dir: Path) -> None:
    """Save a histogram of token counts."""
    flat_tokens = tokens.reshape(-1)
    values, counts = torch.unique(flat_tokens, return_counts=True)

    order = torch.argsort(values)
    values = values[order]
    counts = counts[order]

    out_path = out_dir / f"{name}_hist.png"
    plt.figure(figsize=(12, 4))
    plt.bar(values.detach().cpu().numpy(), counts.detach().cpu().numpy())
    plt.title(f"{name} | token counts")
    plt.xlabel("code id")
    plt.ylabel("count")
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()
    print("Saved:", out_path)


def main() -> None:
    """Load all configured token files and generate summaries and plots."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for filename in FILES:
        path = BASE_DIR / filename
        name = path.stem

        if not path.exists():
            print(f"[SKIP] File does not exist: {path}")
            continue

        loaded = load_tokens(path)
        tokens = extract_token_tensor(loaded)

        if tokens is None:
            print(f"[WARN] {name}: unsupported object type. Adjust parsing for this file format.")
            continue

        summarize_tokens(name, tokens)
        plot_slice(name, tokens, OUT_DIR)
        plot_histogram(name, tokens, OUT_DIR)

    print(f"\nReady. Figures saved in: {OUT_DIR}")


if __name__ == "__main__":
    main()
